title: Manish Agrawal
description: Personal Site
author: Manish Agrawal
github: https://github.com/spaceVStab
about: 
avatar_url: /static/img/my_image.JPG

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/manish_1107"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/manishhag"
    - icon: fa-github
      link: "https://github.com/spacevstab"

share:
  twitter_username: github.io

urls:
    - text: About Me
      url: /about/

url: "https://spacevstab.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
